config/routes.rb
Rails.application.routes.draw do

  resources :accounts
  resources :bank_accounts
  resources :budgets
  resources :categories
  resources :transactions
  resources :users
  

end

app/models/budget.rb
class Budget < ActiveRecord::Base
	belongs_to :accounts
	has_many :categories
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:category_id, :value, :start_date, :end_date, :account_id)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.haml
= form_for @budget do |f|
  - if @budget.errors.any?
    #error_explanation
      %h2= "#{pluralize(@budget.errors.count, "error")} prohibited this budget from being saved:"
      %ul
        - @budget.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :category_id
    = f.text_field :category_id
  .field
    = f.label :value
    = f.text_field :value
  .field
    = f.label :start_date
    = f.text_field :start_date
  .field
    = f.label :end_date
    = f.text_field :end_date
  .field
    = f.label :account_id
    = f.text_field :account_id
  .actions
    = f.submit 'Save'

app/views/budgets/edit.html.haml
%h1 Editing budget

= render 'form'

= link_to 'Show', @budget
\|
= link_to 'Back', budgets_path

app/views/budgets/index.html.haml
%h1 Listing budgets

%table
  %tr
    %th Category
    %th Value
    %th Start date
    %th End date
    %th Account
    %th
    %th
    %th

  - @budgets.each do |budget|
    %tr
      %td= budget.category_id
      %td= budget.value
      %td= budget.start_date
      %td= budget.end_date
      %td= budget.account_id
      %td= link_to 'Show', budget
      %td= link_to 'Edit', edit_budget_path(budget)
      %td= link_to 'Destroy', budget, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Budget', new_budget_path

app/views/budgets/new.html.haml
%h1 New budget

= render 'form'

= link_to 'Back', budgets_path

app/views/budgets/show.html.haml
%p#notice= notice

%p
  %b Category:
  = @budget.category_id
%p
  %b Value:
  = @budget.value
%p
  %b Start date:
  = @budget.start_date
%p
  %b End date:
  = @budget.end_date
%p
  %b Account:
  = @budget.account_id

= link_to 'Edit', edit_budget_path(@budget)
\|
= link_to 'Back', budgets_path