config/routes.rb
Rails.application.routes.draw do

  resources :accounts
  resources :bank_accounts
  resources :budgets
  resources :categories
  resources :transactions
  resources :users
  

end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
	belongs_to :accounts
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]

  # GET /bank_accounts
  # GET /bank_accounts.json
  def index
    @bank_accounts = BankAccount.all
  end

  # GET /bank_accounts/1
  # GET /bank_accounts/1.json
  def show
  end

  # GET /bank_accounts/new
  def new
    @bank_account = BankAccount.new
  end

  # GET /bank_accounts/1/edit
  def edit
  end

  # POST /bank_accounts
  # POST /bank_accounts.json
  def create
    @bank_account = BankAccount.new(bank_account_params)

    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully created.' }
        format.json { render :show, status: :created, location: @bank_account }
      else
        format.html { render :new }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_accounts/1
  # PATCH/PUT /bank_accounts/1.json
  def update
    respond_to do |format|
      if @bank_account.update(bank_account_params)
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_account }
      else
        format.html { render :edit }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_accounts/1
  # DELETE /bank_accounts/1.json
  def destroy
    @bank_account.destroy
    respond_to do |format|
      format.html { redirect_to bank_accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_account_params
      params.require(:bank_account).permit(:name, :type, :balance, :account_id)
    end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/views/bank_accounts/_form.html.haml
= form_for @bank_account do |f|
  - if @bank_account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bank_account.errors.count, "error")} prohibited this bank_account from being saved:"
      %ul
        - @bank_account.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :balance
    = f.text_field :balance
  .field
    = f.label :account_id
    = f.text_field :account_id
  .actions
    = f.submit 'Save'

app/views/bank_accounts/edit.html.haml
%h1 Editing bank_account

= render 'form'

= link_to 'Show', @bank_account
\|
= link_to 'Back', bank_accounts_path

app/views/bank_accounts/index.html.haml
%h1 Listing bank_accounts

%table
  %tr
    %th Name
    %th Type
    %th Balance
    %th Account
    %th
    %th
    %th

  - @bank_accounts.each do |bank_account|
    %tr
      %td= bank_account.name
      %td= bank_account.type
      %td= bank_account.balance
      %td= bank_account.account_id
      %td= link_to 'Show', bank_account
      %td= link_to 'Edit', edit_bank_account_path(bank_account)
      %td= link_to 'Destroy', bank_account, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bank account', new_bank_account_path

app/views/bank_accounts/new.html.haml
%h1 New bank_account

= render 'form'

= link_to 'Back', bank_accounts_path

app/views/bank_accounts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @bank_account.name
%p
  %b Type:
  = @bank_account.type
%p
  %b Balance:
  = @bank_account.balance
%p
  %b Account:
  = @bank_account.account_id

= link_to 'Edit', edit_bank_account_path(@bank_account)
\|
= link_to 'Back', bank_accounts_path