config/routes.rb
Rails.application.routes.draw do

  resources :accounts
  resources :bank_accounts
  resources :budgets
  resources :categories
  resources :transactions
  resources :users
  

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:payee, :amount, :date, :reconciled, :location, :budget_id, :user_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.haml
= form_for @transaction do |f|
  - if @transaction.errors.any?
    #error_explanation
      %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
      %ul
        - @transaction.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :payee
    = f.text_field :payee
  .field
    = f.label :amount
    = f.text_field :amount
  .field
    = f.label :date
    = f.text_field :date
  .field
    = f.label :reconciled
    = f.text_field :reconciled
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :budget_id
    = f.text_field :budget_id
  .field
    = f.label :user_id
    = f.text_field :user_id
  .actions
    = f.submit 'Save'

app/views/transactions/edit.html.haml
%h1 Editing transaction

= render 'form'

= link_to 'Show', @transaction
\|
= link_to 'Back', transactions_path

app/views/transactions/index.html.haml
%h1 Listing transactions

%table
  %tr
    %th Payee
    %th Amount
    %th Date
    %th Reconciled
    %th Location
    %th Budget
    %th User
    %th
    %th
    %th

  - @transactions.each do |transaction|
    %tr
      %td= transaction.payee
      %td= transaction.amount
      %td= transaction.date
      %td= transaction.reconciled
      %td= transaction.location
      %td= transaction.budget_id
      %td= transaction.user_id
      %td= link_to 'Show', transaction
      %td= link_to 'Edit', edit_transaction_path(transaction)
      %td= link_to 'Destroy', transaction, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Transaction', new_transaction_path

app/views/transactions/new.html.haml
%h1 New transaction

= render 'form'

= link_to 'Back', transactions_path

app/views/transactions/show.html.haml
%p#notice= notice

%p
  %b Payee:
  = @transaction.payee
%p
  %b Amount:
  = @transaction.amount
%p
  %b Date:
  = @transaction.date
%p
  %b Reconciled:
  = @transaction.reconciled
%p
  %b Location:
  = @transaction.location
%p
  %b Budget:
  = @transaction.budget_id
%p
  %b User:
  = @transaction.user_id

= link_to 'Edit', edit_transaction_path(@transaction)
\|
= link_to 'Back', transactions_path